### PR TITLE
Use FieldInfo repr. This non-trivially changes how the output is displayed.

### PR DESCRIPTION
**Pull request by mpkocher**
Use Pydantic repr on FieldInfo. I believe this is a reasonable tradeoff for robustness. 

```
usage: example.py --input_file INPUT_FILE --alpha ALPHA --beta BETA --state STATE --name NAME [--help] [--version]

options:
  --input_file INPUT_FILE
                        FieldInfo(annotation=Literal[1, 2], required=True)
  --alpha ALPHA         FieldInfo(annotation=int, required=True, frozen=True)
  --beta BETA           FieldInfo(annotation=int, required=True, metadata=[Gt(gt=0)])
  --state STATE         FieldInfo(annotation=State, required=True, description='The State of the Job to filter on.')
  --name NAME           FieldInfo(annotation=Union[NoneType, str], required=True)
  --help                Print Help and Exit
  --version             show program's version number and exit
```

### CODE REVIEW

**Comment by mpkocher** [comment]
#69 and #68

**Comment by mpkocher** [comment]
This creates some other issues. Any other metadata (e.g., extras) is pushed to the Field and also displayed. 

```python
from pydantic import Field
from pydantic_cli import run_and_exit, Cmd


class Options(Cmd):
    alpha: int = Field(..., cli=('-a', '--alpha'), other=["other metadata"])

    def run(self) -> None:
        print(f"Mock example running with {self}")

if __name__ == "__main__":
    run_and_exit(Options, description=__doc__, version="0.1.0")

```

Yields:

```
usage: b.py -a ALPHA [--help] [--version]

options:
  -a ALPHA, --alpha ALPHA
                        FieldInfo(annotation=int, required=True, json_schema_extra={'cli': ('-a', '--alpha'), 'other': ['other metadata']})
  --help                Print Help and Exit
  --version             show program's version number and exit
```

At a minimum, `cli` needs to be deleted after it's processed. 

It's not clear if the metadata should also be displayed. There arguments for and against displaying it here. 

https://docs.pydantic.dev/latest/api/fields/

The `**kwargs` "extra" is deprecated (which is a bit of another problem with `cli=('-a', '--alpha')`.

**Comment by pavan-uppari** [comment]
A better approach would be to use `__repr_str__` instead of `repr`

with `repr`

```
options:
  --input_file INPUT_FILE
                        FieldInfo(annotation=str, required=True)
  --max_records MAX_RECORDS
                        FieldInfo(annotation=int, required=True)
```

with `__repr_str__`
```
--input_file INPUT_FILE
                        annotation=str required=True
  --max_records MAX_RECORDS
                        annotation=int required=True
```

No need to display FieldInfo in the terminal

@mpkocher

**Comment by mpkocher** [comment]
> No need to display FieldInfo in the terminal
> 
> @mpkocher

I experiment with that but it looked wonky. Specifically for cases where there's a custom description for a field.


```
usage: example.py --input_file INPUT_FILE --alpha ALPHA --beta BETA --state STATE --name NAME [--help] [--version]

options:
  --input_file INPUT_FILE
                        annotation=Literal[1, 2], required=True
  --alpha ALPHA         annotation=int, required=True, frozen=True
  --beta BETA           annotation=int, required=True, metadata=[Gt(gt=0)]
  --state STATE         annotation=State, required=True, description='The State of the Job to filter on.'
  --name NAME           annotation=Union[NoneType, str], required=True
  --help                Print Help and Exit
  --version             show program's version number and exit
```

I'm going to use "Field" and manually create the display. This is perhaps a slight improvement.

```
usage: example.py --input_file INPUT_FILE --alpha ALPHA --beta BETA --state STATE --name NAME [--help] [--version]

options:
  --input_file INPUT_FILE
                        Field(annotation=Literal[1, 2], required=True)
  --alpha ALPHA         Field(annotation=int, required=True, frozen=True)
  --beta BETA           Field(annotation=int, required=True, metadata=[Gt(gt=0)])
  --state STATE         Field(annotation=State, required=True, description='The State of the Job to filter on.')
  --name NAME           Field(annotation=Union[NoneType, str], required=True)
  --help                Print Help and Exit
  --version             show program's version number and exit
```

**Pull request merged**
